version: '3.8'

services:
  app1:
    image: polbro_app1
    build:
      context: .
      args:
        - NEXT_PUBLIC_AUTH_BACKEND_API_URL=${NEXT_PUBLIC_AUTH_BACKEND_API_URL}
        - NEXT_PUBLIC_POLLING_BACKEND_API_URL=${NEXT_PUBLIC_POLLING_BACKEND_API_URL1}
        - NEXT_PUBLIC_POLLING_FRONTEND_API_URL=${NEXT_PUBLIC_POLLING_FRONTEND_API_URL}
    container_name: polbro_app1
    ports:
      - '3000:3000'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  app2:
    image: polbro_app2
    build:
      context: .
      args:
        - NEXT_PUBLIC_AUTH_BACKEND_API_URL=${NEXT_PUBLIC_AUTH_BACKEND_API_URL}
        - NEXT_PUBLIC_POLLING_BACKEND_API_URL=${NEXT_PUBLIC_POLLING_BACKEND_API_URL2}
        - NEXT_PUBLIC_POLLING_FRONTEND_API_URL=${NEXT_PUBLIC_POLLING_FRONTEND_API_URL}
    container_name: polbro_app2
    ports:
      - '3001:3000'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
volumes:
  polling-storage:
